//step 1:define a project schema
const mongoose = require('mongoose');
const Schema=mongoose.Schema;
const projectSchema = new Schema({
    id: { type: String, required: true }, // Note: 'id' is not a standard field in Mongoose; it is usually generated by MongoDB. If you want to use it, ensure it's unique.
    pid: { type: Number, required: true, unique: true },
    title: { type: String, required: true },
    startDate: { type: Date, required: true }, // Note: consistent camelCase (startDate, not startdate)
    dueDate: { type: Date, required: true },  // Note: consistent camelCase (dueDate, not duedate)
   status: { 
        type: String, 
        required: true,
        enum: ['To Do', 'In Progress', 'Done'] // Recommended: add allowed values
    },
    tasks:{
        type:String,required:true
    } 
    
}, { timestamps: true }); // Timestamps are automatically added by Mongoose if timestamps is set to true in the schema options.  This adds createdAt and updatedAt fields to the schema.
//step 2: create a project model

module.exports=mongoose.model('Project', projectSchema)